[package]
name = "lake_mixing_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float = "0.1.2"
plotters = "0.3.5"
iter_num_tools = "0.7.1"
time = {version="0.3.22", features=["macros"]}
